version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: "ecto://postgres:postgres@db/papercups"
      SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
      BACKEND_URL: "${BACKEND_URL}"
      REACT_APP_URL: "${REACT_APP_URL}"
      MIX_ENV: "prod"
      REQUIRE_DB_SSL: "false"
      USE_IP_V6: "false"
    labels:
      traefik.enable: "true"
      traefik.http.routers.papercups_api_http.rule: "Host(`${DOMAIN_API}`)"
      traefik.http.routers.papercups_api_http.entrypoints: "web"
      traefik.http.routers.papercups_api_http.middlewares: "redirect-to-https"
      traefik.http.routers.papercups_api_https.rule: "Host(`${DOMAIN_API}`)"
      traefik.http.routers.papercups_api_https.entrypoints: "websecure"
      traefik.http.routers.papercups_api_https.tls.certresolver: "letsencrypt"
      traefik.http.services.papercups_api.loadbalancer.server.port: "4000"
      traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: "https"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend
    labels:
      traefik.enable: "true"
      traefik.http.routers.papercups_front_http.rule: "Host(`${DOMAIN_FRONT}`)"
      traefik.http.routers.papercups_front_http.entrypoints: "web"
      traefik.http.routers.papercups_front_http.middlewares: "redirect-to-https"
      traefik.http.routers.papercups_front_https.rule: "Host(`${DOMAIN_FRONT}`)"
      traefik.http.routers.papercups_front_https.entrypoints: "websecure"
      traefik.http.routers.papercups_front_https.tls.certresolver: "letsencrypt"
      traefik.http.services.papercups_front.loadbalancer.server.port: "80"
      traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: "https"

  db:
    image: postgres:alpine
    restart: always
    container_name: papercups-db
    volumes:
      - papercups_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  papercups_db:
